"use client";
import React from "react";
import { defaultArticles, defaultClients, defaultProjects, defaultServices, type Article, type Client, type Project, type Service } from "./content";

const load = <T,>(key: string, fallback: T): T => { try { const v = localStorage.getItem(key); return v ? JSON.parse(v) : fallback; } catch { return fallback; } };

export default function Home() {
  const [services, setServices] = React.useState<Service[]>(defaultServices);
  const [clients, setClients] = React.useState<Client[]>(defaultClients);
  const [projects, setProjects] = React.useState<Project[]>(defaultProjects);
  const [articles, setArticles] = React.useState<Article[]>(defaultArticles);
  React.useEffect(() => { setServices(load("modo-services", defaultServices)); setClients(load("modo-clients", defaultClients)); setProjects(load("modo-projects", defaultProjects)); setArticles(load("modo-articles", defaultArticles)); }, []);
  return <main id="top" className="overflow-hidden bg-[#0a0a0a] text-white">
    <nav className="fixed inset-x-0 top-0 z-50 border-b border-white/[0.05] bg-[#0a0a0a]/80 px-6 py-5 backdrop-blur-md md:px-10"><div className="mx-auto flex max-w-[1400px] items-center justify-between"><a href="#top"><img src="/modo-logo.png" alt="MODO Branding Agency" className="w-[100px] md:w-[120px]" /></a><div className="hidden items-center gap-9 text-sm text-neutral-400 md:flex"><a href="#work" className="hover:text-white">Work</a><a href="#services" className="hover:text-white">Services</a><a href="#insights" className="hover:text-white">Insights</a><a href="#about" className="hover:text-white">About</a></div><a href="#contact" className="rounded-full border border-white/20 px-5 py-2.5 text-sm hover:bg-white hover:text-black">Start a project</a></div></nav>

    <section className="relative flex min-h-screen items-end px-6 pb-16 pt-32 md:px-10 md:pb-20"><div className="absolute right-[8%] top-[15%] h-[500px] w-[500px] rounded-full bg-white/[0.025] blur-[100px]"/><div className="relative mx-auto w-full max-w-[1400px]"><div className="mb-10 flex items-center gap-3 text-sm text-neutral-500"><span className="h-2 w-2 rounded-full bg-white animate-pulse"/>Branding · Creative · Digital</div><h1 className="max-w-[1200px] text-[17vw] font-semibold leading-[0.78] tracking-[-0.075em] md:text-[12vw] lg:text-[10.5vw]">MAKE<br/><span className="text-neutral-500">YOUR</span><br/>MODO.</h1><div className="mt-14 flex flex-col justify-between gap-8 md:flex-row md:items-end"><p className="max-w-md text-lg leading-relaxed text-neutral-400 md:text-xl">We build brands, experiences and digital ideas that move businesses forward.</p><a href="#about" className="text-sm text-neutral-500 hover:text-white">Scroll to explore ↓</a></div></div></section>

    <section id="about" className="border-t border-white/10 px-6 py-28 md:px-10 md:py-40"><div className="mx-auto grid max-w-[1400px] gap-16 lg:grid-cols-2"><p className="text-sm uppercase tracking-[0.2em] text-neutral-500">What is MODO?</p><div><h2 className="text-4xl font-medium leading-[1.05] tracking-[-0.04em] md:text-6xl">A branding agency for businesses that <span className="text-neutral-500">refuse to look ordinary.</span></h2><p className="mt-10 max-w-xl text-lg leading-relaxed text-neutral-400">MODO combines strategy, design, content and digital marketing into one creative direction. We do not just make things look good. We make brands feel right.</p></div></div></section>

    <section id="services" className="bg-[#111] px-6 py-28 md:px-10 md:py-40"><div className="mx-auto max-w-[1400px]"><div className="mb-20 flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="mb-5 text-sm uppercase tracking-[0.2em] text-neutral-500">Our capabilities</p><h2 className="text-5xl tracking-[-0.05em] md:text-7xl">What we do.</h2></div><p className="max-w-sm text-neutral-500">From the first idea to the final campaign, we create with purpose.</p></div><div className="divide-y divide-white/10 border-y border-white/10">{services.map(s=><div key={s.number} className="grid gap-5 py-8 md:grid-cols-[100px_1fr_1fr] md:items-start"><span className="text-sm text-neutral-600">{s.number}</span><h3 className="text-2xl md:text-3xl">{s.title}</h3><p className="max-w-md text-neutral-500 leading-relaxed">{s.text}</p></div>)}</div></div></section>

    <section id="work" className="px-6 py-28 md:px-10 md:py-40"><div className="mx-auto max-w-[1400px]"><div className="mb-16 flex items-end justify-between gap-6"><div><p className="mb-5 text-sm uppercase tracking-[0.2em] text-neutral-500">Selected work</p><h2 className="text-5xl tracking-[-0.05em] md:text-7xl">Work that moves.</h2></div><a href="/work" className="hidden text-sm text-neutral-500 hover:text-white md:block">View all work →</a></div><div className="grid gap-px bg-white/10 md:grid-cols-3">{projects.map((p,i)=><a href="/work" key={i} className="min-h-[300px] bg-[#0a0a0a] p-7 transition hover:bg-[#151515] md:p-9"><span className="text-xs uppercase tracking-[0.15em] text-neutral-600">{p.category}</span><h3 className="mt-28 text-3xl tracking-[-0.03em]">{p.title}</h3><p className="mt-4 text-sm leading-relaxed text-neutral-500">{p.description}</p><span className="mt-7 block text-xs text-neutral-700">{p.year}</span></a>)}</div></div></section>

    <section id="insights" className="bg-[#111] px-6 py-28 md:px-10 md:py-40"><div className="mx-auto max-w-[1400px]"><div className="mb-16 flex items-end justify-between gap-6"><div><p className="mb-5 text-sm uppercase tracking-[0.2em] text-neutral-500">Insights</p><h2 className="text-5xl tracking-[-0.05em] md:text-7xl">Ideas worth sharing.</h2></div><a href="/insights" className="hidden text-sm text-neutral-500 hover:text-white md:block">View all insights →</a></div><div className="grid gap-5 md:grid-cols-3">{articles.slice(0,3).map(a=><a href={`/insights/${a.slug}`} key={a.slug} className="group border-t border-white/10 pt-6"><div className="flex justify-between text-xs text-neutral-600"><span>{a.category}</span><span>{a.readTime}</span></div><h3 className="mt-10 text-2xl leading-tight tracking-[-0.02em] group-hover:text-neutral-300">{a.title}</h3><p className="mt-5 text-sm leading-relaxed text-neutral-500">{a.excerpt}</p><div className="mt-8 text-xs text-neutral-700">{a.date}</div></a>)}</div></div></section>

    <section className="px-6 py-28 md:px-10 md:py-40"><div className="mx-auto max-w-[1400px]"><div className="mb-16"><p className="mb-5 text-sm uppercase tracking-[0.2em] text-neutral-500">Selected clients</p><h2 className="text-5xl tracking-[-0.05em] md:text-7xl">Trusted by brands.</h2></div><div className="grid grid-cols-2 gap-px bg-white/10 md:grid-cols-4">{clients.map(c=><div key={c.name} className="flex min-h-[150px] items-center justify-center bg-white p-7"><img src={c.logo} alt={c.name} className="max-h-20 max-w-[150px] object-contain"/></div>)}</div></div></section>

    <section className="border-t border-white/10 px-6 py-28 md:px-10 md:py-40"><div className="mx-auto max-w-[1400px]"><div className="mb-16"><p className="mb-5 text-sm uppercase tracking-[0.2em] text-neutral-500">How we work</p><h2 className="text-5xl tracking-[-0.05em] md:text-7xl">From idea to impact.</h2></div><div className="grid gap-px bg-white/10 md:grid-cols-4">{["Discover","Define","Create","Launch"].map((x,i)=><div key={x} className="bg-[#0a0a0a] p-7 md:min-h-[230px]"><span className="text-xs text-neutral-600">0{i+1}</span><h3 className="mt-16 text-2xl">{x}</h3><p className="mt-3 text-sm leading-relaxed text-neutral-500">{["We understand your business, audience, market and opportunity.","We create the strategic and creative direction for the brand.","We turn the strategy into a clear and powerful visual system.","We put the brand into the world and help it move forward."][i]}</p></div>)}</div></div></section>

    <section id="contact" className="bg-white px-6 py-28 text-black md:px-10 md:py-40"><div className="mx-auto max-w-[1400px]"><p className="text-sm uppercase tracking-[0.2em] text-neutral-500">Start a project</p><h2 className="mt-8 max-w-5xl text-6xl font-medium leading-[0.95] tracking-[-0.06em] md:text-8xl">Your brand deserves more.</h2><a href="mailto:hello@modo.agency" className="mt-12 inline-block rounded-full bg-black px-7 py-4 text-sm text-white">hello@modo.agency ↗</a></div></section>
    <footer className="bg-[#0a0a0a] px-6 py-10 md:px-10"><div className="mx-auto flex max-w-[1400px] items-center justify-between"><img src="/modo-logo.png" alt="MODO" className="w-[90px]"/><span className="text-xs text-neutral-600">© 2026 MODO Branding Agency</span></div></footer>
  </main>;
}
